#!/usr/bin/env bash

# Update the package repository and install curl
sudo apt update && sudo apt-get install -y curl

# Navigate to the user's home directory and create/update .bashrc
cd ~/ && touch .bashrc

# Download and install NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

# Source the updated .bashrc to enable NVM
source ~/.bashrc

# Install Node.js version 18 using NVM
nvm install v18

# Install Yarn globally using npm
npm install --global yarn

# Check and display the versions of NVM, Node, and Yarn
nvm -v && node -v && yarn --version

# Print a success message if NVM and Node versions are displayed
echo "If you see the version of NVM and Node"
echo "That means you successfully installed NVM for Node!"
